Repository UWPCommunity/Quarrel, pull requests merged in 2020-06, with the labels that each got.

#307 Re-encode to png from bmp when attaching bmp
  src/Quarrel/Controls/Messages/MessageBox.xaml.cs
Labels: API, Confirmed bug, bug

#311 Leaving servers
  src/Quarrel.ViewModels/Models/Bindables/Guilds/BindableGuild.cs
  src/Quarrel/DataTemplates/Guilds/GuildTemplate.xaml
Labels: feature pairity, ui

#315 Added Quote flyout option
  src/Quarrel.ViewModels/MainViewModel/MessageBoxMainViewModel.cs
  src/Quarrel/Controls/Messages/MessageFlyout.xaml
Labels: feature pairity, ui

#324 Style cop
  src/Quarrel/Controls/AudioVisualizer.xaml.cs
  src/Quarrel/Controls/Messages/MessageBox.xaml.cs
  src/Quarrel/Controls/MyTubeEmbedWrapper.xaml.cs
  src/Quarrel/Controls/Shell/SideDrawer.xaml.cs
  src/Quarrel/Converters/Base/IntColorToBrushConverter.cs
  src/Quarrel/Converters/Base/IntColorToColorConverter.cs
  src/Quarrel/Converters/Base/UriToImageSourceConverter.cs
  src/Quarrel/Converters/Discord/UserToStringConverter.cs
  src/Quarrel/DataTemplates/FlyoutDictionary.xaml.cs
  src/Quarrel/DataTemplates/MessageBox/SuggestionsTemplate.xaml.cs
  src/Quarrel/DataTemplates/Messages/ReactionTemplate.xaml.cs
  src/Quarrel/Helpers/ItemClickCommandParameter.cs
  src/Quarrel/Services/Resources/ResourceService.cs
  src/Quarrel/Services/Voice/WebrtcManager.cs
  src/Quarrel/SubPages/AddServer/AddServerPage.xaml.cs
  src/Quarrel/SubPages/DiscordStatusPage.xaml.cs
  src/Quarrel/TemplateSelectors/AttachmentTemplateSelector.cs
  src/Quarrel/TemplateSelectors/EmbedTemplateSelector.cs
  src/Quarrel/TemplateSelectors/GuildTemplateSelector.cs
  src/Quarrel/TemplateSelectors/SuggestionTemplateSelector.cs
  src/Quarrel/ViewModels/ViewModelLocator.cs
  src/_APIs/DiscordAPI/Models/Messages/Message.cs
  src/_APIs/DiscordAPI/Voice/IWebrtcManager.cs
Labels: style

#338 Fixed ScrollViewers in settings
  src/Quarrel/SubPages/GuildSettings/Pages/AuditLogSettingsPage.xaml
  src/Quarrel/SubPages/GuildSettings/Pages/ModerationSettingsPage.xaml
  src/Quarrel/SubPages/GuildSettings/Pages/NotificationsSettingsPage.xaml
  src/Quarrel/SubPages/GuildSettings/Pages/OverviewSettingsPage.xaml
  src/Quarrel/SubPages/GuildSettings/Pages/PrivacySettingsPage.xaml
  src/Quarrel/SubPages/UserSettings/Pages/BehaviorSettingsPage.xaml
  src/Quarrel/SubPages/UserSettings/Pages/DisplaySettingsPage.xaml
  src/Quarrel/SubPages/UserSettings/Pages/MyAccountSettingsPage.xaml
  src/Quarrel/SubPages/UserSettings/Pages/PrivacySettingsPage.xaml
  src/Quarrel/SubPages/UserSettings/Pages/VoiceSettingsPage.xaml
Labels: Confirmed bug, bug, ui

#340 Insider indicator in What's New page
  src/Quarrel/App.xaml.cs
  src/Quarrel/SubPages/WhatsNewPage.xaml
  src/Quarrel/SubPages/WhatsNewPage.xaml.cs
Labels: ui

#349 Fixed server list duplicates when reconnecting
  src/Quarrel.ViewModels/Services/Discord/Guilds/GuildsService.cs
Labels: Confirmed bug, bug, ui

#351 Dev optimisations
  src/Quarrel.ViewModels/Services/Analytics/IAnalyticsService.cs
  src/Quarrel/Controls/AudioVisualizer.xaml.cs
  src/Quarrel/Controls/Shell/CurrentUserButton.xaml
  src/Quarrel/Controls/Shell/Views/MessageListControl.xaml
  src/Quarrel/Controls/Shell/VoiceConnection.xaml
  src/Quarrel/DataTemplates/Channels/ChannelTemplate.xaml
  src/Quarrel/DataTemplates/Guilds/GuildTemplate.xaml
  src/Quarrel/Services/Analytics/AppCenterService.cs
  src/Quarrel/Services/Settings/SettingsService.cs
Labels: optimization

#358 Re-finished Russian and Swedish translations
  src/Quarrel/Controls/Shell/ExtendedSplashScreen.xaml.cs
  src/Quarrel/Converters/Profile/PresenceTypeToStatusConverter.cs
  src/Quarrel/Localization/en/MiscStrings.resw
  src/Quarrel/Localization/ru/MiscStrings.resw
  src/Quarrel/Localization/sv/MiscStrings.resw
Labels: localization

#372 Insider release 20.6.19
  src/Quarrel/App.xaml.cs
  src/Quarrel/Converters/Profile/Relationships/RelationToUnblockConverter.cs
  src/Quarrel/Package.appxmanifest
  src/Quarrel/SubPages/UserProfilePage.xaml
Labels: release

#373 Release 20.6.19
  src/Quarrel/App.xaml.cs
  src/Quarrel/Converters/Profile/Relationships/RelationToUnblockConverter.cs
  src/Quarrel/Package.appxmanifest
  src/Quarrel/SubPages/UserProfilePage.xaml
Labels: release

#400 Fixed blank line in some translations of "blocked" pivot
  src/Quarrel/Localization/en/Controls.resw
  src/Quarrel/Localization/es/Controls.resw
  src/Quarrel/Localization/fr/Controls.resw
  src/Quarrel/Localization/it/Controls.resw
  src/Quarrel/Localization/la/Controls.resw
  src/Quarrel/Localization/no/Controls.resw
  src/Quarrel/Localization/pt/Controls.resw
  src/Quarrel/Localization/ro/Controls.resw
Labels: Confirmed bug, bug, localization, ui

#405 FallbackValue for channel topics
  src/Quarrel/Controls/Shell/QuarrelCommandBar.xaml
Labels: Confirmed bug, bug, ui

#407 Change your own nickname
  src/Quarrel.ViewModels/Models/Bindables/Users/BindableGuildMember.cs
  src/Quarrel.ViewModels/SubPages/ChangeNicknameViewModel.cs
  src/Quarrel/Controls/Shell/CurrentUserButton.xaml
  src/Quarrel/DataTemplates/Members/GuildMemberListItemTemplate.xaml
  src/Quarrel/Quarrel.csproj
  src/Quarrel/SubPages/ChangeNicknamePage.xaml
  src/Quarrel/SubPages/ChangeNicknamePage.xaml.cs
  src/Quarrel/ViewModels/ViewModelLocator.cs
  src/_APIs/DiscordAPI/API/Guild/IGuildService.cs
Labels: enhancement, feature pairity
