Repository UWPCommunity/Quarrel, pull requests merged in 2020-07, with the labels that each got.

#413 Fixed quoting with the quote button
  src/Quarrel.ViewModels/MainViewModel/MessageBoxMainViewModel.cs
Labels: bug

#414 Locked channel list headers
  src/Quarrel/Controls/Shell/Views/ChannelListControl.xaml
Labels: ui

#404 Service dilution
  src/Quarrel.ViewModels/Controls/EmojiPickerViewModel.cs
  src/Quarrel.ViewModels/Extensions/DiscordAPI.Gateway.DownstreamEvents/ReadyExtensions.cs
  src/Quarrel.ViewModels/Extensions/DiscordAPI.Models/MutualGuildExtensions.cs
  src/Quarrel.ViewModels/MainViewModel/ChannelsMainViewModel.cs
  src/Quarrel.ViewModels/MainViewModel/GenericMainViewModel.cs
  src/Quarrel.ViewModels/MainViewModel/GuildsMainViewModel.cs
  src/Quarrel.ViewModels/MainViewModel/MembersMainViewModel.cs
  src/Quarrel.ViewModels/MainViewModel/MessagesMainViewModel.cs
  src/Quarrel.ViewModels/Models/Bindables/Channels/BindableChannel.cs
  src/Quarrel.ViewModels/Models/Bindables/Guilds/BindableGuild.cs
  src/Quarrel.ViewModels/Models/Bindables/Guilds/BindableMutualGuild.cs
  src/Quarrel.ViewModels/Models/Bindables/Messages/BindableMessage.cs
  src/Quarrel.ViewModels/Models/Bindables/Messages/Embeds/BindableInvite.cs
  src/Quarrel.ViewModels/Models/Bindables/Users/BindableGuildMember.cs
  src/Quarrel.ViewModels/Models/Bindables/Users/BindableGuildMemberGroup.cs
  src/Quarrel.ViewModels/Services/Discord/Channels/ChannelsService.cs
  src/Quarrel.ViewModels/Services/Discord/Channels/IChannelsService.cs
  src/Quarrel.ViewModels/Services/Discord/Gateway/GatewayService.cs
  src/Quarrel.ViewModels/Services/Discord/Guilds/GuildsService.cs
  src/Quarrel.ViewModels/Services/Discord/Guilds/IGuildsService.cs
  src/Quarrel.ViewModels/SubPages/GuildSettings/Pages/AuditLogSettingsPageViewModel.cs
  src/Quarrel/Converters/AuditLog/AuditLogEntryToMarkdownConverter.cs
  src/_Libs/QuarrelMarkdown/Markdown/Display/XamlRenderer.cs
Labels: optimization, refactor

#419 Metadata update for 20.7.4
  src/Quarrel/Package.appxmanifest
  src/Quarrel/SubPages/WhatsNewPage.xaml
Labels: release

#421 Localization
  appMetadata/release/de/baseListing/metadata.json
  appMetadata/release/es/baseListing/metadata.json
  appMetadata/release/fr/baseListing/metadata.json
  appMetadata/release/it/baseListing/metadata.json
  appMetadata/release/la/baseListing/metadata.json
  appMetadata/release/no/baseListing/metadata.json
  appMetadata/release/pt/baseListing/metadata.json
  appMetadata/release/ro/baseListing/metadata.json
  appMetadata/release/ru/baseListing/metadata.json
  appMetadata/release/sv/baseListing/metadata.json
  src/Quarrel/Localization/de/AddServer.resw
  src/Quarrel/Localization/de/AuditLog.resw
  src/Quarrel/Localization/de/Controls.resw
  src/Quarrel/Localization/de/DataTemplates.resw
  src/Quarrel/Localization/de/GuildSettings.resw
  src/Quarrel/Localization/de/Meta.resw
  src/Quarrel/Localization/de/MiscStrings.resw
  src/Quarrel/Localization/de/MiscSubs.resw
  src/Quarrel/Localization/de/UserSettings.resw
  src/Quarrel/Localization/en/MiscSubs.resw
  src/Quarrel/Localization/es/AddServer.resw
  src/Quarrel/Localization/es/AuditLog.resw
  src/Quarrel/Localization/es/Controls.resw
  src/Quarrel/Localization/es/DataTemplates.resw
  src/Quarrel/Localization/es/GuildSettings.resw
  src/Quarrel/Localization/es/Meta.resw
  src/Quarrel/Localization/es/MiscStrings.resw
  src/Quarrel/Localization/es/MiscSubs.resw
  src/Quarrel/Localization/es/UserSettings.resw
  src/Quarrel/Localization/pt/AddServer.resw
  src/Quarrel/Localization/pt/AuditLog.resw
  src/Quarrel/Localization/pt/Controls.resw
  src/Quarrel/Localization/pt/DataTemplates.resw
  src/Quarrel/Localization/pt/GuildSettings.resw
  src/Quarrel/Localization/pt/Meta.resw
  src/Quarrel/Localization/pt/MiscStrings.resw
  src/Quarrel/Localization/pt/MiscSubs.resw
  src/Quarrel/Localization/pt/UserSettings.resw
  src/Quarrel/Localization/ru/AddServer.resw
  src/Quarrel/Localization/ru/AuditLog.resw
  src/Quarrel/Localization/ru/Controls.resw
  src/Quarrel/Localization/ru/DataTemplates.resw
  src/Quarrel/Localization/ru/GuildSettings.resw
  src/Quarrel/Localization/ru/Meta.resw
  src/Quarrel/Localization/ru/MiscStrings.resw
  src/Quarrel/Localization/ru/MiscSubs.resw
  src/Quarrel/Localization/ru/UserSettings.resw
  src/Quarrel/Localization/sv/AddServer.resw
  src/Quarrel/Localization/sv/AuditLog.resw
  src/Quarrel/Localization/sv/Controls.resw
  src/Quarrel/Localization/sv/DataTemplates.resw
  src/Quarrel/Localization/sv/GuildSettings.resw
  src/Quarrel/Localization/sv/Meta.resw
  src/Quarrel/Localization/sv/MiscStrings.resw
  src/Quarrel/Localization/sv/MiscSubs.resw
  src/Quarrel/Localization/sv/UserSettings.resw
  src/Quarrel/Quarrel.csproj
  src/Quarrel/SubPages/ChangeNicknamePage.xaml
Labels: localization

#433 Fixed error where guilds can show in the reversed order
  src/Quarrel.ViewModels/MainViewModel/GuildsMainViewModel.cs
Labels: Confirmed bug, bug, ui

#447 Commands for UserProfile actions
  src/Quarrel.ViewModels/Models/Bindables/Users/BindableGuildMember.cs
  src/Quarrel/SubPages/UserProfilePage.xaml
Labels: Confirmed bug, bug, ui

#455 Support for previewing GIFV and improvements to their display
  src/Quarrel.ViewModels/SubPages/AttachmentPageViewModel.cs
  src/Quarrel/DataTemplates/Messages/MessageTemplate.xaml
  src/Quarrel/SubPages/AttachmentPage.xaml
  src/Quarrel/SubPages/AttachmentPage.xaml.cs
  src/_APIs/DiscordAPI/Interfaces/IPreviewableImage.cs
  src/_APIs/DiscordAPI/Models/Messages/Embeds/Attachment.cs
  src/_APIs/DiscordAPI/Models/Messages/Embeds/Embed.cs
Labels: Confirmed bug, bug, optimization, ui
